### ISSUE TITLE
clmbr_compute_representations create multiple patient representations for the same index time

### ISSUE THREAD

**Issue by guolin1** [som-shahlab/femr#101]
## Describe the bug
`clmbr_compute_representations` can sometimes create multiple patient representations for the same index time, leading to extra rows in the feature matrix or mismatch in the number of patient representations and the number of labels.

## Steps to reproduce the bug
Jupyter notebook for demonstration: `/local-scratch/nigam/projects/lguo/femr-test/featurize.ipynb`

- tested using `piton_new3_extract` 

## Environment info
`conda activate /local-scratch/nigam/envs/lguo/femr` (latest femr pull)

**Comment by Lalaland** [comment]
I think I just fixed this with https://github.com/som-shahlab/femr/pull/102. Can you do me a favor and test your notebook from scratch again from the latest commit?

**Comment by guolin1** [comment]
looks good. Thanks!
