### ISSUE TITLE
Better error handling for PatientDatabase constructor

### ISSUE THREAD

**Issue by scottfleming** [som-shahlab/femr#105]
**Is your feature request related to a problem? Please describe.**
Error messages for loading a PatientDatabase object with an invalid argument are cryptic and unhelpful

**Describe the solution you'd like**
Better error handling and a more clear description of the problem e.g., "Path passed to PatientDatabase constructor was invalid: {invalid path}"

![Screen Shot 2023-03-14 at 2 59 25 PM](https://user-images.githubusercontent.com/11773823/225150443-7590f099-0a2a-42c0-8e26-de3f2fc570fd.png)

**Comment by Lalaland** [comment]
piton.datasets.PatientDatabase(None) now returns a better error message. The non existent directory error still needs to get improved.
