### ISSUE TITLE
Add more flexible `filter` kwarg to `CountFeaturizer`

### ISSUE THREAD

**Issue by Miking98** [som-shahlab/femr#106]
**Is your feature request related to a problem? Please describe.**
Instead of just filtering codes by `excluded_codes` in `CountFeaturizer`, allow users to filter codes via an arbitrary callback function i.e. `filter = lambda event: True if event.table == 'obs' else False` which takes as input an `event` and returns `True/False`.

**Describe the solution you'd like**
Add `filter: Callable` as kwarg to `CountFeaturizer.__init__()`

**Comment by ericpan64** [comment]
Started looking into this -- at which point would you want the filter callback to be executed?

In the example above, the `event` parameter in the callback seems to be an object of some sort that isn't a code or set of codes itself (thus it will need more context of some sort?)

If this is a common workflow then this should be added as a feature of some sort
