### ISSUE TITLE
extractors.omop.OMOP_BIRTH is misspecified

### ISSUE THREAD

**Issue by guolin1** [som-shahlab/femr#119]
## Describe the bug
OMOP_BIRTH is used in Stanford transforms (e.g., `transforms.stanford.move_pre_birth()`) to search for birth events in patient timelines. However, OMOP_BIRTH is specified as an OMOP concept ID (4216316), and is being matched with FEMR codes (event.code). Consequently, no birth events are actually returned. 

## Steps to reproduce the bug
```python
from piton.extractors.omop import OMOP_BIRTH

PATH_TO_EXTRACT="/local-scratch/nigam/projects/ethanid/shared_tutorial_files/piton_new3_extract"
database = PatientDatabase(PATH_TO_EXTRACT)
ontology = database.get_ontology()

for i in range(1000):
    patient = database[i]
    for event in patient.events:
        if event.code == OMOP_BIRTH:
            print(event.start)
```

## Expected results
Prints birth date for each patient.

## Actual results
Nothing.

## Workaround
Use the correct code, which in the extract version above is `219`. However, the code might change across extract version(?). 
``` Python
ontology.get_dictionary()[219] 
>>> 'SNOMED/3950001'
```

## Environment info
`Conda environment: /local-scratch/nigam/envs/lguo/femr`

**Comment by Lalaland** [comment]
There is an issue here, in that the documentation is poor, but it's not technically a bug.

The problem is that event.code is originally OMOP concept_ids, it's just that they get remapped later.

So the transform does work, it's just that it works for confusing reasons.

**Comment by guolin1** [comment]
I see. Thanks for the explanation! Closing the issue.
