### ISSUE TITLE
`clmbr_create_batches` transformer_vocab_size requirement

### ISSUE THREAD

**Issue by guolin1** [som-shahlab/femr#124]
## Describe the bug
`clmbr_create_batches` asserts `transformer_vocab_size` <= `len(dictionary)` instead of a specific key-value pair that contains the actual code dictionary, e.g., `len(dictionary['ontology_rollup']` or `len(dictionary['regular'])`. Should the assertion use ontology rollup?

**Comment by Lalaland** [comment]
Oh, oops. Wasn't tested properly. Fixed and pushed.
