### ISSUE TITLE
Develop example femr refactor prototype

### ISSUE THREAD

**Issue by Lalaland** [som-shahlab/femr#133]
The goal is to experiment having the `PatientCollection` and `PatientDatabase` abstractions in Python and avoid writing to disc steps

Also have some ideas on using functional programming concepts to make the ETL step more transparent which I want to explore (e.g. keeping functions "pure" and focusing on the input/output of each step)

**Comment by Lalaland** [comment]
@ericpan64 

> The goal is to experiment having the PatientCollection and PatientDatabase abstractions in Python and avoid writing to disc steps

PatientCollection is already 100% Python. 

Converting PatientDatabase to Python is an interesting question, but I think would be difficult. @Miking98 looked into this, did you come to any conclusions about this?

> Also have some ideas on using functional programming concepts to make the ETL step more transparent which I want to explore (e.g. keeping functions "pure" and focusing on the input/output of each step)


What does this even mean? The patient transform system is already pure functional programming. The extraction steps are also very close.

**Comment by ericpan64** [comment]
> What does this even mean? The patient transform system is already pure functional programming. The extraction steps are also very close.

Imo reading/writing to disk makes a function "unpure", and requires the programmer to think about their filesystem instead of focusing purely on the Python logic. I do agree there's a lot of good examples of functional programming in the repo already

**Comment by Lalaland** [comment]
> Imo reading/writing to disk makes a function "unpure"

It's not possible to store all of our raw patient data in memory so they have to be shunted to disk ASAP

**Comment by ericpan64** [comment]
Update: shared example in FEMR group meeting yesterday, will re-iterate and make higher fidelity
