### ISSUE TITLE
make femr_visit_detail_concept_id optional

### ISSUE THREAD

**Issue by guolin1** [som-shahlab/femr#149]
**Is your feature request related to a problem? Please describe.**
The current ETL expects a custom `femr_visit_detail_concept_id` consists of `care_site_id` and `place_of_service_concept_id` (currently requires an additional ETL) in the visit_detail and uses that field instead of `visit_detail_concept_id` which specifies, e.g., patient class. This seems like a stanford-specific choice made that prefers the encoding of care site (institution specific) instead of the standard visit detail concepts. For the SK ETL, I actually modified the code locally to use visit_detail_concept_id. 

**Describe the solution you'd like**
An option for the ETL to use either and defaults to visit_detail_concept_id

**Describe alternatives you've considered**
Make the creation of of `femr_visit_detail_concept_id` as a `femr.transforms` that users can add to their ETLs.

**Comment by Lalaland** [comment]
Does visit_detail_concept_id actually contain anything meaningful at Sickkids? At Stanford it does not.

**Comment by Lalaland** [comment]
By meaningful, I mean more informative that visit_concept_id.

**Comment by guolin1** [comment]
At SK, the visit_detail_concept_id specifies patient class for each transfer event. So for visit_concept_id 262 (Emergency room and inpatient visit), you can use the visit_detail_concept_id to figure when the patient class was switched to inpatient.

**Comment by Lalaland** [comment]
Looking the Stanford tables again, I think discarding visit_detail_concept_id for Stanford was actually a mistake.

It was broken in earlier versions of STARR-OMOP, but it now seems to be functioning correctly and does provide useful information that is not present in visit_concept_id.

Also, your suggestion would improve OMOP compliance quite a bit. 

Let me write a PR to eliminate femr_visit_detail_concept_id and I will write the care_site fix later.
