### ISSUE TITLE
Improve error handling for non-list labels in `LabeledPatients` 

### ISSUE THREAD

**Issue by scottfleming** [som-shahlab/femr#170]
## Describe the bug
If you create a `LabeledPatients` object that maps from patient ID's to labels rather than mapping from patient ID's to _**lists**_ of labels then there is no error on instantiation but the subsequent error message is opaque.

## Steps to reproduce the bug
```python
labels = femr.labelers.LabeledPatients({0: femr.labelers.Label(time=datetime.now(), value=False)})
labels.save('tmp.csv')
```

## Expected results
There should be error handling on creation of `femr.labelers.LabeledPatients`. A message like, "Error: the label map you passed to instantiate the LabeledPatients object maps from integer patient ID's to Labels. It should map from integers to Iterables of Labels instead." would be helpful.

## Actual results
```*** TypeError: 'Label' object is not iterable```

**Comment by lingping-fuzzy** [comment]
from femr.labelers import load_labeled_patients, LabeledPatients, Label
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: cannot import name 'load_labeled_patients' from 'femr.labelers' (site-packages\femr\labelers\__init__.py),
could you tell me what is this error, how to fix it. thank you
