### ISSUE TITLE
How can I apply the motor model?

### ISSUE THREAD

**Issue by clzhang123** [som-shahlab/femr#175]
Thank you for your excellent paper! 
From the paper, I understand that the model should be used from "femr/tutorials/reference/2_apply_motor_model", but I was not able to find this file. Could you please advise on how I should use the model?

**Comment by EthanSteinberg** [comment]
@clzhang123 thanks for the interest! We'll be uploading the model within a month or so to Huggingface (as well as updated tutorials). The link will be in the camera ready version of the paper and I'll also post here when it is ready.
