### ISSUE TITLE
birth code mismatch

### ISSUE THREAD

**Issue by ZepengHuo** [som-shahlab/femr#178]
When running MOTOR tutorial on INSPECT cohort, there's a birth code problem.

The path to code `/share/pi/nigam/projects/zphuo/repos/femr/tutorials/6_Train_MOTOR_INSPECT.py`

The bug 

`ValueError: Couldn't find patient birthdate -- Patient has no birth events (which must be {meds.birth_code})`
but birthcode `SNOMED/3950001` is present, jut not `SNOMED/184099003`

**Comment by pascalvenema** [comment]
Hi @ZepengHuo,

I see this issue has been closed. However, it seems that I still run into this issue (probably on an old version of MEDS). Do you know if it has been fixed in a new release?

Best,
Pascal

**Comment by ZepengHuo** [comment]
You probably want to re-do the ETL process with the newest [MEDS_ETL](https://github.com/Medical-Event-Data-Standard/meds_etl) so that the birth code is correct for patients.

Tagging @EthanSteinbergPrealize for double checking
