### ISSUE TITLE
bug in femr.featurizers.core.preprocess_featurizers

### ISSUE THREAD

**Issue by duncanmcelfresh** [som-shahlab/femr#185]
bug here: https://github.com/som-shahlab/femr/blob/eb33adbf89f49d7c1d4488042d8e3ee2fc0a50fb/src/femr/featurizers/core.py#L266C34-L266C34

femr.featurizers.core.preprocess_featurizers uses partial() to call function _preprocess_agg_func with kwargs "label_map" and "featurizers". but function _preprocess_agg_func takes two positional args: "first"
 and "second"

**Comment by EthanSteinbergPrealize** [comment]
@duncanmcelfresh This is a bug in femr in that we shouldn't be using functools.partial for arguments that aren't necessary.

However, it's unclear why this broke on your machine as partial is explicitly designed to support extra arguments.

My guess is that you are running on a very old (or very new version of Python)?

**Comment by EthanSteinbergPrealize** [comment]
https://github.com/som-shahlab/femr/commit/d67b4c113b343819c5eb3e65685c60c384f57d8a should fix things.
