### ISSUE TITLE
Time conversion backward compatibility 

### ISSUE THREAD

**Issue by ZepengHuo** [som-shahlab/femr#211]
Imon has run into ETL issues of `femr.featurizers.join_labels` where there's consistent 1 day gap, so joining the features and labels will give error. Per her description, it's the time stamp conversion from FEMR v1 to always have UTC but not for v2. So presumably the labeling are done on v1 and featurization is on v2. If this is a FEMR issue then we can discuss.

From Imon:

> It strange that I have 1 day difference between feature_times and label["prediction_time"].

**Comment by EthanSteinberg** [comment]
I'm not sure what the bug would be? All the timestamps used within FEMR should be "naive" timestamps, with no timezone attached (either UTC or otherwise)
