### ISSUE TITLE
Suggest in README that users create a new environment

### ISSUE THREAD

**Issue by scottfleming** [som-shahlab/femr#216]
**Is your feature request related to a problem? Please describe.**
If you install `numpy` with conda on macOS then you may run into the following error when you try to train a tokenizer:
```
OMP: Error #15: Initializing libiomp5.dylib, but found libomp.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
Abort trap: 6
```
This can be solved by starting from a new, fresh conda environment and installing `femr` first, which will download everything from pip and avoid this issue.

**Describe the solution you'd like**
Suggest that users start from a fresh environment in the README.

**Comment by EthanSteinberg** [comment]
I think that's standard knowledge and doesn't need to be in documentation like this
