### ISSUE TITLE
fEMR website is blank

### ISSUE THREAD

**Issue by angiemarie** [som-shahlab/femr#223]
The http://www.teamfemr.org website is either down or expired.
The community Slack link also leads to a blank site: http://teamfemr.org/slack.html

The last working snapshot of the site on Wayback Machine is from June 08, 2023.
The latest snapshot on May 28, 2024 also shows the website is not working properly.

**Comment by EthanSteinberg** [comment]
I think you got this repository confused for another project?

**Comment by angiemarie** [comment]
Hi Ethan,
I did indeed. The other project is FEMR - Fast Electronic Medical Records. Whoops!
