### ISSUE TITLE
Add patient `metadata`

### ISSUE THREAD

**Issue by Miking98** [som-shahlab/femr#25]
**Is your feature request related to a problem? Please describe.**
Add attributes to `Patient` object (birth date, gender, ethnicity) + ability to add arbitrary attributes.

**Describe the solution you'd like**
Add a special `Event` to the beginning of a `Patient` object with datetime = 0 which contained, as its `metadata` field, the values for the parent `Patient`'s `metadata`.

**Comment by Lalaland** [comment]
@Miking98 This is now possible due to the latest refactor. Still not sure how you wanted this to look like
