### ISSUE TITLE
Rename `piton` to something more descriptive.

### ISSUE THREAD

**Issue by Miking98** [som-shahlab/femr#26]
**Is your feature request related to a problem? Please describe.**
Though I do like the CLMBR/piton combo, the name `piton` sounds a bit confusingly close to "Python", and it's not immediately obvious what the `piton` library accomplishes from the name. This will make marketing the tool / getting organic traffic harder.

**Describe the solution you'd like**
Change the name to something like `ehrpy` or `ehr2seq` or `ehr-io` (or even `ehr-ml`) so that its immediately obvious what the library is -- a Python library for using EHRs for machine learning.

I'm sure we can come up with better names than those listed above as well.

**Describe alternatives you've considered**
There are already libraries named `ehrapy`, `pyhealth`, and `pyehr`.

**Comment by Lalaland** [comment]
I'm still a big fan of the ehr_ml name (as shown by my previous choice!)

**Comment by jason-fries** [comment]
We should consider other names (`piton` was always the internal development name IMO) but we absolutely cannot use a hyphenated name like `ehr-ml` as the package name. You also want to pick a name that isn't bloodless and generic.
