### ISSUE TITLE
Some transformations need to occur within the extraction pipeline -- leaky abstraction

### ISSUE THREAD

**Issue by Miking98** [som-shahlab/femr#32]
**Is your feature request related to a problem? Please describe.**
When extracting events from MIMIC-III, some events do not have an associated date (i.e. just an `hadm_id` mapping the event to an admission), and thus the end user must choose an arbitrary time for the event (typically mapping it to the end date of the admission). Currently, we assume that **transformations** of data take in  patient timeline, and output a modified patient timeline. This assumes that you have already materialized a patient timeline by the time you apply transformations. However, because of this `hadm_id` vagueness, there is no way to map these events to a patient timeline without first applying a transformation that turns these `hadm_id`'s into datetimes (because otherwise you won't know what date on the timeline to map the event to). Thus, you need to implicitly add a transformation into your extraction pipeline before you can map it to a patient timeline

**Describe the solution you'd like**
Not sure. Seems like there are two stages of transformation -- pre-extraction and post-extraction.

May need to re-think our mental model of the ETL pipeline.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Lalaland** [comment]
Yeah, this is an existing issue. https://github.com/som-shahlab/piton/tree/main/tools is where I am storing transforms of this type.

The trick is designing an API that can support this type of thing.

**Comment by Miking98** [comment]
Haven't fully thought this through, but one proposed solution:

We could just make `start = Optional[datetime.datetime]`, and `start` could be `None` up to the point where you create a `PatientDatabase`. That way you don't need to know apriori where an event has to map when you are doing extractions. 

Concretely, you'd 
1. create a bunch of `Event` objects with `hadm_id` attributes and `start = None`
2. create your `EventCollection` as normal
3. create your `PatientCollection` as normal (here, you'd just append `Events` where `start = None` to the start/end of the patient timeline, doesn't really matter)
4. run your sequence of transformations on these patient timelines to convert `hadm_id` -> an actual `start` time.
5. create your `PatientDatabase`, and only here enforce that `start != None`

This requires slightly redefining the contract of what properties an `Event` can have at each stage, but may be cleaner in that it avoids the need to do a pre-extraction transformation

**Comment by jason-fries** [comment]
This proposal looks more like the original workflow that I pitched at the beginning of the Fall where you assume the master join has already been completed before applying transformations. Assuming all transformations are applied to the collection of events comprising a single patient's timeline seems like a cleaner abstraction IMO.

**Comment by Lalaland** [comment]
@Miking98 I feel like I don't understand your transform enough to really comment on whether that would be a good solution. Let's punt on this until I write an OMOP-MIMIC converter which might give me some more insight here. I'm really hesitant to make Event.start nullable though, it would cause a lot of annoyance elsewhere in the codebase. Seems like this would be better handled with modifications to the CSVReader api.
