### ISSUE TITLE
Add documentation for `extension/datasets.pyi`

### ISSUE THREAD

**Issue by Miking98** [som-shahlab/femr#4]
Would be great to add documentation / type checking for the functions in `extension/datasets.pyi` since its not immediately obvious what these methods do from the code.

**Comment by Miking98** [comment]
Also, can we rename `Dictionary` to be `Array` or something -- the current name is confusing given its accessed via an integer index into a list of values.

**Comment by Lalaland** [comment]
The key part of Dictionary is that it also supports fast inverse lookups. I think using the name Array would mask that.

**Comment by Lalaland** [comment]
We really need https://github.com/python/mypy/pull/13284 to do this right.

**Comment by scottfleming** [comment]
@Lalaland speaking of this, Line 10 in the current tutorial throws an error on the `main` branch for me. @Miking98 are you also hitting this issue?
