### ISSUE TITLE
Make specifying an ontology optional + document what is currently expected

### ISSUE THREAD

**Issue by Miking98** [som-shahlab/femr#40]
**Is your feature request related to a problem? Please describe.**
In order to create a PatientDatabase, you must specify an ontology. i.e.
```
patient_collection.to_patient_database(
    patient_database_dir,
    path_to_ontology_dir,
    num_threads=num_threads,
).close()
```

where `path_to_ontology_dir` must contain a file called **concept.csv**, and each unique event code belonging to a patient must be included in this file.

If I don't want / have an ontology (e.g. audit log events, flowsheet events), then I will still be forced to construct this file by making up entries in it. This is problematic for two reasons:

1. It creates unnecessary extra work for the end user before they are able to use Piton.
2. The core functionality of Piton (iterating through a patient timeline) should be independent of any ontology-related considerations

**Describe the solution you'd like**
Ability to not specify an ontology and just load timelines, like in [PyHealth](https://pyhealth.readthedocs.io/en/latest/api/datasets/pyhealth.datasets.MIMIC3Dataset.html).

**Describe alternatives you've considered**
Internally, the easiest change would be for Piton to just create a dummy `concept.csv` file and fill it with event codes. This seems very hacky. A better solution would just be to remove the requirement for the user to specify an ontology and to disentangle ontology-related functionality from the rest of the library.

**Comment by Miking98** [comment]
As a first step, documenting what Piton expects from the ontology-standpoint would be super helpful as well (i.e. what the folder structure of `path_to_ontology_dir` must be at a minimum).

My current understanding:
```
path_to_ontology_dir/
    concepts/
        concepts.csv.zst # Must contain every event code in your patient database
        concept_relationship.csv.zst # Can be blank
```

**Comment by Lalaland** [comment]
100% agree that this should be better documented.

The current setup (once https://github.com/som-shahlab/piton/pull/42 is merged) is that 

path_to_ontology_dir must contain either a folder called concepts, or a file of either concepts.csv.zst or concepts.csv

It can, but doesn't need to contain, a file/folder called concept_relationship. (If it doesn't exist, the code will assume that there are no relationships between the concepts).

> If I don't want / have an ontology (e.g. audit log events, flowsheet events), then I will still be forced to construct this file by making up entries in it. This is problematic for two reasons:

The behavior will be very poorly defined if we don't get at minimum a concepts.csv file. I don't think it's good to support / encourage that. When you call get_code_dictionary(), what should it return? There are no good options there.

**Comment by Lalaland** [comment]
This is currently handled by the MIMIC + simple format tutorials.
