### ISSUE TITLE
More obvious way to map Piton codes -> text descriptions

### ISSUE THREAD

**Issue by Miking98** [som-shahlab/femr#53]
**Is your feature request related to a problem? Please describe.**
To convert a Piton code to an English description, you need to do something like: `ontology.get_dictionary()[539]` which is not super obvious.

**Describe the solution you'd like**
`ontology.convert_name_from_piton_code(539)` which would yield 'Visit/IP' or something like that

**Comment by Lalaland** [comment]
Done as Piton/FEMR codes are now gone.
