### ISSUE TITLE
Move multiprocessing into the featurizer code, and expose via an `n_jobs` parameter

### ISSUE THREAD

**Issue by Miking98** [som-shahlab/femr#57]
**Is your feature request related to a problem? Please describe.**
We should discuss whether it makes sense to hide the multiprocessing within featurizers and expose them to an end user via eg. `n_jobs` parameter (this seems like the simplest possible interface) versus requiring the end user to set up the multiprocessing plumbing around these featurizers. If the former, then we should restructure the other featurizers to be more like this NoteFeaturizer, if the latter then we'll need to change NoteFeaturizer to be more like the others.

**Comment by Lalaland** [comment]
This is now done.
