### ISSUE TITLE
Ability to read/write from `EventCollection` and `PatientCollection` without wrapping in a context

### ISSUE THREAD

**Issue by Miking98** [som-shahlab/femr#62]
**Is your feature request related to a problem? Please describe.**
There should be a function within `EventCollection` and `PatientCollection` that handles the context for you, and just accepts a list of patients or events. The `with contextlib.closing(eventcollection.writer()) as writer` notation is super confusing for newcomers.

**Describe the solution you'd like**
A function like `eventcollection.add_events(List[Event])`

**Comment by Lalaland** [comment]
As a separate thing, maybe we should try to eliminate contextlib.closing and instead have writer directly return a context manager?

**Comment by Miking98** [comment]
I think both would be great improvements!
