### ISSUE TITLE
Replace "dill @ git+https://github.com/som-shahlab/dill@enums" in `pyproject.toml` with "dill = 0.3.7" when patch for 

### ISSUE THREAD

**Issue by Miking98** [som-shahlab/femr#72]
## Describe the bug
When this issue is resolved: https://github.com/uqfoundation/dill/issues/332

Replace our forked version of dill (with the abstract method patch) with the official dill version.

Specifically, we are waiting on this pull request to be released: https://github.com/uqfoundation/dill/pull/450

**Comment by Lalaland** [comment]
Dill is now removed.
