### ISSUE TITLE
Consistent Naming

### ISSUE THREAD

**Issue by Miking98** [som-shahlab/femr#74]
**Is your feature request related to a problem? Please describe.**
1. `EventCollection` and `PatientCollection` are confusing b/c they don't literally describe what they are. `UnorderedEventList` and `OrderedEventList` seem like more accurate names?
1. Should a piton output be called `extract` or `PatientDatabase` or `Database` ? Should be consistent in what we refer to it as

**Comment by Miking98** [comment]
@Lalaland  thoughts / other ideas for naming conventions?

**Comment by Lalaland** [comment]
@Miking98 I think EventCollection and PatientCollection are better since they describe what is being stored and what the api supports.

EventCollections contain events. PatientCollections contain patients.

**Comment by Lalaland** [comment]
@Miking98 Is this still a live issue, or can we close this?
