### ISSUE TITLE
What makes an event a billing code, and how did we converge on the current decision?

### ISSUE THREAD

**Issue by scottfleming** [som-shahlab/femr#76]
**Is your feature request related to a problem? Please describe.**
I'm confused about how we decided what is/is not a billing code. Based on https://github.com/som-shahlab/piton/blob/main/src/piton/transforms/stanford.py#L149, it seems like we currently say that everything from the `pat_enc_dx`, `hsp_acct_dx_list`, and `arpb_transactions` tables in EPIC clarity (no clear one-to-one mappings from these tables to OMOP tables) is a billing code. Do we have any reference with this information and the source?

**Describe the solution you'd like**
It'd be nice to have a comment in the code stating how/why we decided these tables are considered billing codes (e.g., is this from RIT? private conversation with Jose Posada?)

**Additional context**
Trying to build a benchmark dataset where the user tries to predict billing codes given discharge summaries.

**Comment by Lalaland** [comment]
That's based on the original clarity queries that were used to form stride. I do not have access to those queries any more though so can't cite them.
