### ISSUE TITLE
Labelers do not return labels

### ISSUE THREAD

**Issue by guolin1** [som-shahlab/femr#93]
## Describe the bug
Labelers do not return labels - tested on lab value-based labelers.

## Steps to reproduce the bug on Nero
```python
import os
import pickle
from subprocess import run

## run labelers and featurizers from tutorial
PATH_STDOUT = '/local-scratch/nigam/projects/lguo/femr-test/stdout'
PATH_FEATURES = '/local-scratch/nigam/projects/lguo/femr-test/data/features/'
PATH_EXTRACT = '/local-scratch/nigam/projects/mwornow/data/1_perct_extract_01_11_23'

labelers = ['thrombocytopenia_lab','anemia_lab','hypoglycemia_lab']

os.makedirs(PATH_STDOUT, exist_ok=True)
os.makedirs(PATH_FEATURES, exist_ok=True)

for labeler in labelers:
    
    PATH_OUTPUT = os.path.join(PATH_FEATURES,labeler)
    with open(os.path.join(PATH_STDOUT,f'run_featurizer_{labeler}'),'w') as stdout:

        run(
            [
                'python3', '/local-scratch/nigam/projects/lguo/femr/tutorials/1_run_featurizers.py',
                PATH_EXTRACT,
                PATH_OUTPUT,
                '--labeling_function', labeler,
                '--max_labels_per_patient', '5',
                '--num_threads', '20'
            ],
            stdout=stdout
        )

## no labels assigned
for labeler in labelers:
    
    PATH_OUTPUT = os.path.join(PATH_FEATURES,labeler)
    
    with open(os.path.join(PATH_OUTPUT,'labeled_patients.pkl'),'rb') as f:
        labeled_patients = pickle.load(f)

    with open(os.path.join(PATH_OUTPUT,'featurized_patients.pkl'),'rb') as f:
        featurized_patients = pickle.load(f)
        
    num_labels = labeled_patients.get_num_labels()
    print(f"{labeler} {num_labels=}")
    print(featurized_patients)
```

## Expected results
labeled_patients.get_num_labels() should return >0 labels across all patients

## Actual results
labeled_patients.get_num_labels() returns 0 labels 

## Environment info
Use the following conda environment:
```conda activate /local-scratch/nigam/envs/lguo/femr```

**Comment by guolin1** [comment]
It seems like the issue is related to inpatient admissions not properly filtered / defined:

```python
for p,patient in enumerate(database):
    out = get_inpatient_admission_events(patient, ontology)
    if out: print(patient.patient_id)
```
Returns 0 patients with inpatient admissions. 

[This line](https://github.com/som-shahlab/femr/blob/main/src/piton/labelers/omop.py#L48) defines inpatient admissions as concept code "Visit/IP" and Event.omop_table = "visit_occurrence". However, when you look at an Event with the piton code equivalent of "Visit/IP" (in my case it's 539), the omop_table stored is "visit":

`Event(start=xxx, code=539, omop_table=visit, clarity_table=lpch_pat_enc, visit_id=xxx, end=xxx, source_code=xxx)`

**Comment by guolin1** [comment]
Indeed, changing 
```Python 
if e.code in admission_codes and e.omop_table == "visit_occurrence":
``` 
to 

```Python 
if e.code in admission_codes and e.omop_table == "visit":
``` 
resolves both issues above. 

I can do a PR for this, along with a minor typo fix in `1_run_featurizer.py` tutorial notebook.

**Comment by Lalaland** [comment]
You are running on an old, buggy 1% extract. Can you retry your analysis with "/local-scratch/nigam/projects/ethanid/shared_tutorial_files/piton_new3_extract"

This is a good indication that we need to better maintain and document canonical 1% extracts for each major extract version. Let me create an issue for that.

**Comment by guolin1** [comment]
You're right. Event contains the correct omop_table using piton_new3_extract. Will abandon PR and close the issue!

**Comment by Lalaland** [comment]
Thanks for bringing this up though. We need better signals that people are using old extracts. I think I'm going to add a console warning as well for older extracts.

**Comment by guolin1** [comment]
No problem!
